os: unstable
image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

install:
  - choco install opencv -version 3.4.0

before_build:
  - SET ARCH=x64
  - SET APP_PATH=%CD%
  - IF EXIST C:\tools\OpenCV* CD C:\tools*
  - SET OPENCV_ROOT_PATH=%CD%\opencv
  - CD %APP_PATH%
  - SET OPENCV_DIR=%OPENCV_ROOT_PATH%\build\%ARCH%\vc14
  - SET QTDIR=C:\Qt\5.7\msvc2015_64
  - mkdir external
  - cd external
  - git clone https://github.com/davisking/dlib.git
  - cd dlib
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -T host=x64 -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config Release --target INSTALL
  - SET dlib_DIR=%CD%\install\lib\cmake\dlib
  - ls %dlib_DIR%
  - cd ../../..
  - ls

build_script:
  - cd build
  - echo %OPENCV_DIR%
  - echo %QTDIR%
  - echo %dlib_DIR%
  - ps: $file = "$pwd\deploy.zip"
  - ps: (new-object System.Net.WebClient).Downloadfile("https://github.com/livecv/live-pm/archive/master.zip", $file)
  - ps: 7z x -y $file -o"."
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - mv live-pm-master/* .
  - python --version
  - python livepm/main.py build .. msvc2015_64
  - python livepm/main.py deploy .. msvc2015_64
  - dir
